syntax = "proto3";

package uni.grpc.user;
option java_multiple_files = true;
option java_package = "uni.grpc.user";

service UserService {
    rpc CreateOrGetUser (CreateOrGetUserRequest) returns (UserResponse);
    rpc GetUserById (GetUserByIdRequest) returns (UserResponse);
    rpc GetUserByUsername (GetUserByUsernameRequest) returns (UserResponse);
    rpc UpdateUser (UpdateUserRequest) returns (UserResponse);
    rpc CreateSession (CreateSessionRequest) returns (CreateSessionResponse);
    rpc RefreshSession (RefreshSessionRequest) returns (RefreshSessionResponse);
}

message CreateOrGetUserRequest {
    string email_google = 1;
    string name = 2;
    string surname = 3;
    string avatar_url = 4;
}

message GetUserByIdRequest {
    string id = 1;
}

message GetUserByUsernameRequest {
    string username = 1;
}

message UpdateUserRequest {
    string id = 1;
    optional string username = 2;
    optional string name = 3;
    optional string surname = 4;
    optional string patronymic = 5;
    optional string status = 6;
    optional string avatar_url = 7;
}

message UserResponse {
    string id = 1;
    string email_google = 2;
    string username = 3;
    string name = 4;
    string surname = 5;
    string patronymic = 6;
    string email_university = 7;
    string avatar_url = 8;
    string status = 9;
    bool is_student_verified = 10;
    bool is_employee_verified = 11;
    string created_at = 12;
}

message CreateSessionRequest {
  string user_id = 1;
  string refresh_token = 2;
  int64 expires_in_days = 3;
}

message CreateSessionResponse {
  bool success = 1;
}

message RefreshSessionRequest {
  string old_refresh_token = 1;
}

message RefreshSessionResponse {
  string user_id = 1;
  string new_refresh_token = 2;
}